services:
  - type: web
    name: agro-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m bot.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: RUN_MODE
        value: webhook
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_IDS
        value: 5476913898
      - key: GEMINI_MODEL
        value: gemini-1.5-flash
    plan: free
